version: "3.1"
services:
  glm_test:
    image: jrossusgs/glm3r:v0.6_GLM_3.2.0a3_bugfix
    build:
      context: .
    ports:
      - "8787:8787"
    environment:
      - ROOT=TRUE
      - PASSWORD=mypass
